petshop/pet_adoption/pet_adoption/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('master/',views.Master,name ='master'),
    path('',views.Index,name ='index'),
    # path('index',views.Index,name ='index'),
    path('signup',views.signup,name='signup'),
    path('login',views.login,name='login'),
    # path('signup', views.signup, name='signup'),
    path('/login1',include('django.contrib.auth.urls')),
    path('signin', views.signin, name='signin'),
    path('signin_2', views.signin_2, name='signin_2'),
    path('login1', views.login1, name='login1'),
    path('signout', views.signout, name='signout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    # path('product',views.product_page,name='product'),
    path('product/',views.product_page,name='product'),
    path('product/<str:id>',views.product_details,name='product_details'),
    path('service/',views.service,name='service'),
    path('services',views.services,name='services'),
    path('about',views.about,name='about'),     

    path('adopt/',views.adopt,name='adopt'),
    path('adopt/<str:id>',views.adopt_details,name='adopt_details'),
    path('adopt_page',views.adopt_page,name='adopt_page'),
    path('adoptform',views.adoptform,name='adoptform'),
    path('formsubmition',views.formsubmition,name='formsubmition'),
    path('Servicesumbit',views.Servicesumbit,name='Servicesumbit'),
    path('checkout/',views.CheckOut,name='checkout'),

    path('try1',views.try1,name='try1'),

#     cart
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart_detail/',views.cart_detail,name='cart_detail'),
    path('search/', views.Search, name='search'),
    path('contact_us',views.contact_page,name='contact_page'),
    path('success', views.success, name='success'),
#   blog start
    path('blog', views.blog, name='blog'),
    path('blog', views.blog, name='blog'),
    path('trainpuppy', views.trainpuppy, name='trainpuppy'),
    path('nerdycat', views.nerdycat, name='nerdycat'),
    path('catbreed', views.catbreed, name='catbreed'),
    path('dogbreeder', views.dogbreeder, name='dogbreeder')
    # later delete(only for testing)
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

petshop/pet_adoption/app/models.py
# Create your models here.
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
import datetime

# from matplotlib.style import available

class product_Category(models.Model):
    name = models.CharField(max_length=150)

    def  __str__(self):
        return self.name

class product_Sub_Category(models.Model):
    name = models.CharField(max_length=150)

    product_category = models.ForeignKey(product_Category,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Product(models.Model):
    # Availability = (('In Stock ','In Stock' ),('Out of Stock','Out of Stock'))
    category = models.ForeignKey(product_Category,on_delete=models.CASCADE,null=True)
    sub_category = models.ForeignKey(product_Sub_Category, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='ecomerce/pimg',null=True,blank=True)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    # Availability = models.CharField(choices=Availability,null=True,max_length=100)
    date = models.DateField(auto_now_add= True)
    stock = models.IntegerField()

    def __str__(self):
        return self.name

class pet_Category(models.Model):
    name = models.CharField(max_length=150)

    def  __str__(self):
        return self.name



class breed_Category(models.Model):
    name = models.CharField(max_length=150)

    petCategory = models.ForeignKey(pet_Category,on_delete=models.CASCADE)

    def __str__(self):
        return self.name



class Adopt(models.Model):
    GENDER_CHOICES = (
        ('M' , 'Male'),
        ('F' , 'Female'),
    )
    yes_no_choices=(
        ('y','Yes'),
        ('n','No'),
    )
    age_choices = (
        ('p','Puppyhood'),
        ('a','Adolescence'),
        ('ad','Adulthood'),
        ('s','Senior'),
    )
    available_choices = (
        ('y','Yes'),
        ('in','Inprocess'),
        ('n','No'),
    )
    petCategory = models.ForeignKey(pet_Category,on_delete=models.CASCADE,null=True)
    Breed = models.ForeignKey(breed_Category, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='ecomerce/adopt_img/',null=True,blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)   
    # birthdate = models.CharField(max_length=100)
    location = models.CharField(max_length=10000)
    age = models.CharField(max_length=2, choices=age_choices)
    vacinated = models.CharField(max_length=1, choices=yes_no_choices)
    vaccineinfo = models.CharField(max_length=100 , default='DHPP')
    neutered_or_spayed = models.CharField(max_length=1, choices=yes_no_choices)
    contact_info = models.IntegerField(default='987654321')
    good_with_dogs = models.CharField(max_length=1, choices=yes_no_choices,default='y')
    good_with_kids = models.CharField(max_length=1, choices=yes_no_choices)
    shots_upto_date = models.CharField(max_length=1, choices=yes_no_choices)
    needs_loving_adopter = models.CharField(max_length=1, choices=yes_no_choices,default='y')
    is_available = models.CharField(max_length=100 ,default='yes')
    def __str__(self):
        return self.name

class Order(models.Model):
    image = models.ImageField(upload_to='ecomerce/order/image')
    product =  models.CharField(max_length=1000, default='')
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    quantity = models.CharField(max_length=10)
    price = models.IntegerField()
    total = models.CharField(max_length=100,default='')
    payment_id = models.CharField(max_length=100, default=''),
    paid = models.BooleanField(default=False)
    # first_name = models.CharField(max_length=15)
    # last_name = models.CharField(max_length=15)
    # city = models.CharField(max_length=20)
    # phone = models.CharField(max_length=10)
    # pincode = models.CharField(max_length=6)
    # address  = models.TextField()

    # class Order(models.Model):
    #     image = models.ImageField(upload_to='ecomerce/order/image')
    #     product = models.CharField(max_length=1000, default='')
    #
    #     user = models.ForeignKey(User, on_delete=models.CASCADE)
    #     quantity = models.IntegerField(max_length=10)
    #     price = models.IntegerField()
    #     total = models.CharField(max_length=100, default='')
    #     date = models.DateField(default=datetime.datetime.today)
    #
    #     def __str__(self):
    #         return self.product


    date = models.DateField(default=datetime.datetime.today)


    def __str__(self):
        return self.product



class Responses(models.Model):
    username=models.CharField(max_length=100)
    responsibilty=models.CharField(max_length=100)
    scaretaker=models.CharField(max_length=100)
    lalone=models.CharField(max_length=100)
    firstime=models.CharField(max_length=100)
    petname=models.CharField(max_length=100)

class Services(models.Model):
    name = models.CharField(max_length=150)
    def  __str__(self):
        return self.name


class ServiceResponses(models.Model):
    name=models.CharField(max_length=100)
    # forreq=models.CharField(max_length=100)
    email=models.CharField(max_length=100)
    detailedreq=models.CharField(max_length=1000)
    service = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    contact_info = models.CharField(max_length=100,default='987654321') 
    # firstime=models.CharField(max_length=100)
    # petname=models.CharField(max_length=100)
    def __str__(self):
        return self.name




# registration wala
class details(models.Model):
    username=models.CharField(max_length=100)
    contact=models.IntegerField()
    address=models.CharField(max_length=100)
    email=models.CharField(max_length=100)

class contact_us(models.Model):
    name = models.CharField(max_length=50)
    email =models.EmailField(max_length=50)
    subject =models.CharField(max_length=200)
    message =models.TextField(max_length=200)

    def __str__(self):
        return self.name

petshop/pet_adoption/templates/about.html
{% extends 'master.html' %}

{% block body %}


{% endblock %}

petshop/pet_adoption/templates/adopt.html
{% extends 'master.html' %}
{% block body %}

    <!-- Products Start -->
    <!-- <div class="container-fluid py-5">
        <div class="container">
            <div class="border-start border-5 border-primary ps-5 mb-5" style="max-width: 600px;">
                <h6 class="text-primary text-uppercase">Products</h6>
                <h1 class="display-5 text-uppercase mb-0">Products For Your Best Friends</h1>
            </div>
            <div class="owl-carousel product-carousel">
                {% for prod in product %}
                <div class="pb-5">
                    <div class="product-item position-relative bg-light d-flex flex-column text-center">
                        <img class="img-fluid mb-4" src="{{prod.image}}" alt="">
                        <h6 class="text-uppercase">{{prod.name}}</h6>
                        <h5 class="text-primary mb-0">₹{{prod.price}}</h5>
                        <div class="btn-action d-flex justify-content-center">
                            <a class="btn btn-primary py-2 px-3" href="{% url 'cart_add' prod.id %}"><i class="bi bi-cart"></i></a>
                            <a class="btn btn-primary py-2 px-3" href=""><i class="bi bi-eye"></i></a>
                        </div>
                    </div>

                </div>
                {% endfor %}
            </div>
        </div>
    </div> -->
    <!-- Products End -->



    <div class="container-fluid py-5">
        <div class="container">
            <div class="border-start border-5 border-primary ps-5 mb-5" style="max-width: 600px;">
                <h6 class="text-primary text-uppercase">Products</h6>
                <h1 class="display-5 text-uppercase mb-0">Products For Your Best Friends</h1>
            </div>
            <!-- <div class="owl-carousel product-carousel"> -->
            <div class="row">
             <div class="col-lg-3">

                <!-- Search Form End -->
                <div class="containter" style="margin-top:1.7rem">
                    
                </div>
                <!-- Category Start -->
                <div class="mb-5">
                    <h3 class="text-uppercase border-start border-5 border-primary ps-3 mb-224" style="margin-bottom: 1.1rem;">Categories</h3>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="h5 bg-light py-2 px-3 mb-2" href="{% url 'adopt' %}"><i class="bi bi-arrow-right me-2"></i>All</a>
                        {% for cat in category %}
                        <a class="h5 bg-light py-2 px-3 mb-2" href="/adopt/?category={{cat.id}}"><i class="bi bi-arrow-right me-2"></i>{{cat.name}}</a>
                        {% endfor %}
                    </div>
                </div>
                 <div id="{{cat.id}}" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<!-- {% for i in cat.product_sub_category_set.all %}
											<li><a href="/?category={{i.id}}">{{ i.name}}  </a></li>
											{% endfor %} -->

										</ul>

									</div>
								</div>
             </div>
             <div class="col-lg-9">
                <div class="row">
                    <div class="col-lg-6">
                    </div>
                    <div class="col-lg-6">
                    <!-- <div class="mb-2 w-75" style="float:right;">
                       <form method="get" action="/search/">
							{% csrf_token %}
                        <div class="input-group">
                            <input  name = "query" type="text" class="form-control p-3" placeholder="Search">
                        </div>
                    </form>
                </div> -->
                <!-- <button class="btn btn-primary px-4"><i class="bi bi-search"></i></button>-->
                </div>
                </div>

         
                <div class="row">
                    {% for adopt in adopt %}
                <div class="col-lg-4 my-3">

                    <div class="product-item position-relative bg-light d-flex flex-column text-center">
                        <img class="img-fluid mb-4" src="/{{adopt.image}}" alt="" style="height: 280px; width:230px">
                        <h6 class="text-Camelcase">{{adopt.name}}</h6>
                        <h6 class="text-primary mb-0">{{adopt.location}}</h6>
                        <div class="btn-action d-flex justify-content-center">
                            <a class="btn btn-primary py-2 px-3" href="{% url 'adoptform' %}"><i class="bi bi-cart"></i> adopt </a>
                            <a class="btn btn-primary py-2 px-3" href="{{ adopt.id }}"><i class="bi bi-eye"></i></a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
             </div>
            </div>
        </div>
    </div>






    <!-- Offer Start -->
    <div class="container-fluid bg-offer my-5 py-5">
        <div class="container py-5">
            <div class="row gx-5 justify-content-start">
                <div class="col-lg-7">
                    <div class="border-start border-5 border-dark ps-5 mb-5">
                        <h6 class="text-dark text-uppercase">Special Offer</h6>
                        <h1 class="display-5 text-uppercase text-white mb-0">Save 50% on all items your first order</h1>
                    </div>
                    <p class="text-white mb-4">Eirmod sed tempor lorem ut dolores sit kasd ipsum. Dolor ea et dolore et at sea ea at dolor justo ipsum duo rebum sea. Eos vero eos vero ea et dolore eirmod et. Dolores diam duo lorem. Elitr ut dolores magna sit. Sea dolore sed et.</p>
                    <a href="" class="btn btn-light py-md-3 px-md-5 me-3">Shop Now</a>
                    <a href="" class="btn btn-outline-light py-md-3 px-md-5">Read More</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Offer End -->


    <!-- Pricing Plan Start -->
    <div class="container-fluid py-5">
        <div class="container">
            <div class="border-start border-5 border-primary ps-5 mb-5" style="max-width: 600px;">
                <h6 class="text-primary text-uppercase">Pricing Plan</h6>
                <h1 class="display-5 text-uppercase mb-0">Competitive Pricing For Pet Services</h1>
            </div>
            <div class="row g-5">
                <div class="col-lg-4">
                    <div class="bg-light text-center pt-5 mt-lg-5">
                        <h2 class="text-uppercase">Basic</h2>
                        <h6 class="text-body mb-5">The Best Choice</h6>
                        <div class="text-center bg-primary p-4 mb-2">
                            <h1 class="display-4 text-white mb-0">
                                <small class="align-top"
                                    style="font-size: 22px; line-height: 45px;">₹</small>4900<small
                                    class="align-bottom" style="font-size: 16px; line-height: 40px;">/
                                    Mo</small>
                            </h1>
                        </div>
                         <div class="text-center p-4">
                            <div class="d-flex align-items-center justify-content-between mb-1">
                                <span>Lorem, ipsum dolor.</span>
                                <i class="bi bi-check2 fs-4 text-primary"></i>
                            </div>
                            <div class="d-flex align-items-center justify-content-between mb-1">
                                <span>Lorem, ipsum dolor.</span>
                                <i class="bi bi-check2 fs-4 text-primary"></i>
                            </div>
                            <div class="d-flex align-items-center justify-content-between mb-1">
                                <span>Lorem, ipsum dolor.</span>
                                <i class="bi bi-x fs-4 text-danger"></i>
                            </div>
                            <div class="d-flex align-items-center justify-content-between mb-1">
                                <span>Lorem, ipsum dolor.</span>
                                <i class="bi bi-x fs-4 text-danger"></i>
                            </div>
                            <a href="" class="btn btn-primary text-uppercase py-2 px-4 my-3">Order Now</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="bg-light text-center pt-5">
                        <h2 class="text-uppercase">Standard</h2>
                        <h6 class="text-body mb-5">The Best Choice</h6>
                        <div class="text-center bg-dark p-4 mb-2">
                            <h1 class="display-4 text-white mb-0">
                                <small class="align-top"
                                    style="font-size: 22px; line-height: 45px;">₹</small>9900<small
                                    class="align-bottom" style="font-size: 16px; line-height: 40px;">/
                                    Mo</small>
                            </h1>
                        </div>
                        <div class="text-center p-4">
                            <div class="d-flex align-items-center justify-content-between mb-1">
                                <span>Lorem, ipsum dolor.</span>
                                <i class="bi bi-check2 fs-4 text-primary"></i>
                            </div>
                            <div class="d-flex align-items-center justify-content-between mb-1">
                                <span>Lorem, ipsum dolor.</span>
                                <i class="bi bi-check2 fs-4 text-primary"></i>
                            </div>
                            <div class="d-flex align-items-center justify-content-between mb-1">
                                <span>Lorem, ipsum dolor.</span>
                                <i class="bi bi-check2 fs-4 text-primary"></i>
                            </div>
                            <div class="d-flex align-items-center justify-content-between mb-1">
                                <span>Lorem, ipsum dolor.</span>
                                <i class="bi bi-x fs-4 text-danger"></i>
                            </div>
                            <a href="" class="btn btn-primary text-uppercase py-2 px-4 my-3">Order Now</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="bg-light text-center pt-5 mt-lg-5">
                        <h2 class="text-uppercase">Extended</h2>
                        <h6 class="text-body mb-5">The Best Choice</h6>
                        <div class="text-center bg-primary p-4 mb-2">
                            <h1 class="display-4 text-white mb-0">
                                <small class="align-top"
                                    style="font-size: 22px; line-height: 45px;">₹</small>14900<small
                                    class="align-bottom" style="font-size: 16px; line-height: 40px;">/
                                    Mo</small>
                            </h1>
                        </div>
                         <div class="text-center p-4">
                            <div class="d-flex align-items-center justify-content-between mb-1">
                                <span>Lorem, ipsum dolor.</span>
                                <i class="bi bi-check2 fs-4 text-primary"></i>
                            </div>
                            <div class="d-flex align-items-center justify-content-between mb-1">
                                <span>Lorem, ipsum dolor.</span>
                                <i class="bi bi-check2 fs-4 text-primary"></i>
                            </div>
                            <div class="d-flex align-items-center justify-content-between mb-1">
                                <span>Lorem, ipsum dolor.</span>
                                <i class="bi bi-check2 fs-4 text-primary"></i>
                            </div>
                            <div class="d-flex align-items-center justify-content-between mb-1">
                                <span>Lorem, </span>
                                <i class="bi bi-check2 fs-4 text-primary"></i>
                            </div>
                            <a href="" class="btn btn-primary text-uppercase py-2 px-4 my-3">Order Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Pricing Plan End -->
{% endblock %}

petshop/pet_adoption/templates/adopt_details.html
{% extends 'master.html' %}
{% load crispy_forms_tags %}
{% block body %}



<!-- Blog Start -->
<div class="container py-5">
    <div class="row g-5">
        <div class="col-lg-5">
           
            <div class="mb-5">
                <img class="img-fluid w-75 rounded mb-5 mx-auto d-block" src="/{{adopt.image}}" alt="">

            </div>

        </div>

        <!-- Sidebar Start -->
        <div class="col-lg-7">
            <div class="mb-5">
                <h3 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">About Pet</h3>
                <div class="d-flex flex-column justify-content-start">
                    <!-- we can make this hover:green by using a tag instead of div tag -->
                    <div class="h5 bg-light py-2 px-3 mb-2">Name     - {{adopt.name}}</div>
                    <div class="h5 bg-light py-2 px-3 mb-2">Location - {{adopt.location}}</div>
                    <div class="h5 bg-light py-2 px-3 mb-2">Breed    - {{adopt.Breed}}</div>
                    <div class="h5 bg-light py-2 px-3 mb-2">Type     - {{adopt.petCategory}}</div>  
                    <div class="h5 bg-light py-2 px-3 mb-2">Status   - {{adopt.is_available}}</div>  
                    
                    <div class="h5 bg-light py-2 px-3 mb-2">Age     -  {% if adopt.age == 'p' %} Puppyhood {% elif adopt.age == 'a' %} Adolescence {% elif adopt.age == 'ad' %} Adulthood {% else %} Senior {% endif %}</div>
                    <div class="h5 bg-light py-2 px-3 mb-2">Gender     - {% if adopt.gender == 'M' %} Male {% else %} Female {% endif %}</div>
                    <div class="h5 bg-light py-2 px-3 mb-2">Vaccine Name     - {{adopt.vaccineinfo}}</div>  
                        <div class="row mt-1">
                            <div class="h5 bg-light col-lg-4">Vaccinated {% if adopt.vacinated == 'y' %}  <i class="fa fa-check" style="color:#7AB730"></i> {% else %} <i class="fa fa-close" style="color:#7AB730"></i> {% endif %}</div>
                            <div class="h5 bg-light col-lg-4">Spayed or Neutered {% if adopt.neutered_or_spayed == 'y' %} <i class="fa fa-check" style="color:#7AB730"></i> {% else %} <i class="fa fa-close" style="color:#7AB730"></i> {% endif %}</div>
                            <div class="h5 bg-light col-lg-4">Good with dogs {% if adopt.good_with_dogs == 'y' %} <i class="fa fa-check" style="color:#7AB730"></i> {% else %} <i class="fa fa-close" style="color:#7AB730"></i> {% endif %}</div>
                            <div class="h5 bg-light col-lg-4">Good with kids {% if adopt.good_with_kids == 'y' %} <i class="fa fa-check" style="color:#7AB730"></i> {% else %} <i class="fa fa-close" style="color:#7AB730"></i> {% endif %}</div>
                            <div class="h5 bg-light col-lg-4">Shots upto date {% if adopt.shots_upto_date == 'y' %} <i class="fa fa-check" style="color:#7AB730"></i> {% else %} <i class="fa fa-close" style="color:#7AB730"></i> {% endif %}</div>
                            <div class="h5 bg-light col-lg-4">Needs loving adopter {% if adopt.needs_loving_adopter == 'y' %} <i class="fa fa-check" style="color:#7AB730"></i> {% else %} <i class="fa fa-close" style="color:#7AB730"></i> {% endif %}</div>
                        </div>
                    <!-- <a class="h5 bg-light py-2 px-3 mb-2" href="#">Medical Certificate</a>
                    <a class="h5 bg-light py-2 px-3 mb-2" href="#">Location</a> -->
                    <a href="{% url 'adoptform' %}" class="btn btn-primary text-uppercase py-2 px-4 my-3 w-30 mx-auto d-block">adopt now</i></a>
                </div>
            </div>

        </div>
        <!-- Sidebar End -->
    </div>
</div>
<!-- Blog End -->

{% endblock %}

petshop/pet_adoption/templates/adoptform.html
{% extends 'master.html' %}
{% block body %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/adoptform.css' %}">
<div class="megacontainer">
    <div class="row" style="margin-top: 3rem;">
    <div class="col-lg-1">

    </div>
       <div class="col-lg-11">
        <div class="border-start border-5 border-primary ps-5 mb-5 mx-auto d-block " style="max-width: 600px;">
            <h6 class="text-primary text-uppercase">Adoption</h6>
            <h1 class="display-5 text-uppercase mb-0" style="color: black;">Want to adopt?</h1>
            <!-- <h6 class="display-5 text-uppercase mb-0" style="color: black;">Answer these questions</h6> -->
            <h1>Answer these questions</h1>                     
        </div>
    <p>&nbsp;</p>                            
    <p>Thank you for your interest in adopting a pet from the Paws n Claws! The following information is required so that we can assist you in the selection of your new pet. This form and a consultation with an AWF adoption counselor is designed to help us determine if the adoption is in the animal’s best interest and to assist you in finding the pet most compatible with your lifestyle.</p>
    <p>&nbsp;</p>
    <form action="formsubmition" method="post">
        {% csrf_token %}
        <label for="petname">Which pet you want to adopt</label>
        <select name="petname" id="firstime" class="mx-auto d-block w-25">
            {% for adopt in adopt %}
            <option value="{{adopt.name}}">{{adopt.name}}</option>
            {% endfor %}
            <!-- <option value="no">No</option> -->
        </select>
        <label for="responsibilty">Who will be responsible for the dog's care (feeding, exercise, training, potty walks, vet visits, socialization etc)? *</label>

        <input type="text" name="responsibilty" id="responsibilty" placeholder="Enter Your Answer"  required >
       <label for="scaretaker">Who will provide for your pet in the event that you become ill or unable to care for him/her? *</label>
       <input type="text" name="scaretaker" id="scaretaker" placeholder="Enter Your Answer">
       <label for="lalone">How many hours a day will your dog be left alone? *</label>
       <input type="text" name="lalone" id="lalone" placeholder="Enter Your Answer">
       <label for="firstime">Will this be your first pet? *</label>
       <select name="firstime" id="firstime" class="mx-auto d-block">
           <option value="yes">Yes</option>
           <option value="no">No</option>
       </select>
       <p>&nbsp;</p>

       <input type="submit" value="submit" class="btn btn-primary py-2 px-3 mx-auto d-block" style="margin-left: 470px;
       text-align: center;
       width: 270px;
       background-color: #7AB730;
       border-radius:5px;
   ">
    
    
    </form>
</div>
</div>
</div>
{% endblock %}

petshop/pet_adoption/templates/email_confirmation.html
{% autoescape off %}

 Welcome rocket stock market Simulator!!
 Hello {{ username }}!!
 Please confirm your email by clicking on the following link.

 Confirmation Link: http://{{ domain }}{% url 'activate' uidb64=uid token=token %} 

 {% endautoescape %}

petshop/pet_adoption/templates/product_details.html
{% extends 'master.html' %}
{% load crispy_forms_tags %}
{% block body %}



<!-- Blog Start -->
<div class="container py-5">
    <div class="row g-5">
        <div class="col-lg-5">
           
            <div class="mb-5">
                <img class="img-fluid w-75 rounded mb-5 mx-auto d-block" src="/{{product1.image}}" alt="">

            </div>

        </div>

        <!-- Sidebar Start -->
        <div class="col-lg-7">
            <div class="mb-5">
                <h3 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">Product Details</h3>
                <div class="d-flex flex-column justify-content-start">
                    <a class="h5 bg-light py-2 px-3 mb-2" href="#">{{product1.name}}</a>
                    <a class="h5 bg-light py-2 px-3 mb-2" href="#">₹{{product1.price}}</a>
                    <a class="h5 bg-light py-2 px-3 mb-2" href="#">{{product1.category}}</a>
                    <!-- <a class="h5 bg-light py-2 px-3 mb-2" href="#">Medical Certificate</a>
                    <a class="h5 bg-light py-2 px-3 mb-2" href="#">Location</a> -->
                    <a href="{% url 'cart_add' product1.id %}" class="btn btn-primary text-uppercase py-2 px-4 my-3 w-30 mx-auto d-block">Add to Cart <i class="bi bi-cart"></i></a>
                </div>
            </div>  

        </div>
        <!-- Sidebar End -->
        <div class="col-lg-1">

        </div>
        <div class="col-lg-11">
            <h4 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">More Products</h4>
            <div class="owl-carousel product-carousel">
                {% for prod1 in product2 %}
                <div class="pb-5">
                    <div class="product-item position-relative bg-light d-flex flex-column text-center">
                        <img class="img-fluid mb-4" src="/{{prod1.image}}" alt="">
                        <h6 class="text-uppercase">{{prod1.name}}</h6>
                        <h5 class="text-primary mb-0">₹{{prod1.price}}</h5>
                        <div class="btn-action d-flex justify-content-center">
                            <a class="btn btn-primary py-2 px-3" href=""><i class="bi bi-cart"></i></a>
                            <a class="btn btn-primary py-2 px-3" href=""><i class="bi bi-eye"></i></a>
                        </div>
                    </div>

                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<!-- Blog End -->

{% endblock %}